//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guia
    {
        public string OrigemGuia { get; set; }
        public string NumeroGuia { get; set; }
        public int AnoGuia { get; set; }
        public string Processo { get; set; }
        public string DigProcesso { get; set; }
        public short AnoProcesso { get; set; }
        public string DestinoGuia { get; set; }
        public string DataGuia { get; set; }
        public string SeqGuia { get; set; }
        public string ProcessoFilho { get; set; }
        public string DigitoProcessoFilho { get; set; }
        public Nullable<int> AnoProcessoFilho { get; set; }
        public string SeqProcessoFilo { get; set; }
        public Nullable<bool> Devolvido { get; set; }
        public Nullable<bool> Processado { get; set; }
        public Nullable<bool> Digitalizado { get; set; }
        public Nullable<bool> Erro { get; set; }
        public Nullable<System.DateTime> DataImportacao { get; set; }
    }
}
