//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequencialGed
    {
        public int Numero { get; set; }
        public int DV { get; set; }
        public int Ano { get; set; }
        public string NomeArquivo { get; set; }
        public int Sequencial { get; set; }
    }
}
