//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDummy
    {
        public string um { get; set; }
        public string dois { get; set; }
        public string tres { get; set; }
        public string quatro { get; set; }
        public string cinco { get; set; }
        public string seis { get; set; }
        public string sete { get; set; }
        public string oito { get; set; }
        public string nove { get; set; }
        public string dez { get; set; }
        public string onze { get; set; }
        public string doze { get; set; }
        public string treze { get; set; }
        public Nullable<System.DateTime> DataImportacao { get; set; }
    }
}
